COMP: Fix DCMTK build error on Clang 3.1 on MacOSX
This commit fixes build error introduced by previous commit by updating
the version of DCMTK.

Updated version of DCMTK includes this commit:

//--------------
commit commontk/DCMTK@ade7e93
Author: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
Date:   Wed Sep 30 15:24:53 2015 -0400

    Fix dcmsr build error on clang 3.1 on MacOSX. See Slicer/Slicer#359

    This commit fixes the build error reported below by explicitly
    instantiating the DSRTree<DSRDocumentTreeNode>.

    Build error happening using Clang 3.1 downloaded from [1]
    on MacOSX SnowLeopard:

    //---------------
    $ make cmr/fast  VERBOSE=1
    make -f dcmsr/libcmr/CMakeFiles/cmr.dir/build.make dcmsr/libcmr/CMakeFiles/cmr.dir/build
    Linking CXX shared library ../../lib/libcmr.dylib
    cd /Users/kitware/Dashboards/Continuous/Slicer-0-build/DCMTK-build/dcmsr/libcmr && "/Users/kitware/Dashboards/Support/CMake 3.0.1.app/Contents/bin/cmake" -E cmake_link_script CMakeFiles/cmr.dir/link.txt --verbose=1
    "/Users/kitware/Dashboards/Support/CMake 3.0.1.app/Contents/bin/ctest" --launch --target-name cmr --build-dir /Users/kitware/Dashboards/Continuous/Slicer-0-build/DCMTK-build/dcmsr/libcmr --output ../../lib/libcmr.3.6.1.dylib --target-type SHARED_LIBRARY --language CXX -- /usr/bin/clang++    -fvisibility=hidden -D_XOPEN_SOURCE_EXTENDED -D_BSD_SOURCE -D_BSD_COMPAT -D_OSF_SOURCE -D_DARWIN_C_SOURCE -fPIC -O3 -DNDEBUG -arch x86_64 -isysroot /Developer/SDKs/MacOSX10.6.sdk -mmacosx-version-min=10.6 -dynamiclib -Wl,-headerpad_max_install_names   -compatibility_version 7.0.0 -current_version 3.6.1 -o ../../lib/libcmr.3.6.1.dylib -install_name /Users/kitware/Dashboards/Continuous/Slicer-0-build/DCMTK-build/lib/libcmr.7.dylib CMakeFiles/cmr.dir/init.cc.o CMakeFiles/cmr.dir/logger.cc.o CMakeFiles/cmr.dir/srnumvl.cc.o CMakeFiles/cmr.dir/tid1001.cc.o CMakeFiles/cmr.dir/tid1204.cc.o CMakeFiles/cmr.dir/tid1600.cc.o CMakeFiles/cmr.dir/cid11.cc.o CMakeFiles/cmr.dir/cid29.cc.o CMakeFiles/cmr.dir/cid29e.cc.o CMakeFiles/cmr.dir/cid42.cc.o CMakeFiles/cmr.dir/cid100.cc.o CMakeFiles/cmr.dir/cid244.cc.o CMakeFiles/cmr.dir/cid244e.cc.o CMakeFiles/cmr.dir/cid4020.cc.o CMakeFiles/cmr.dir/cid4021.cc.o CMakeFiles/cmr.dir/cid4031.cc.o CMakeFiles/cmr.dir/cid4031e.cc.o CMakeFiles/cmr.dir/cid5000.cc.o CMakeFiles/cmr.dir/cid5001.cc.o CMakeFiles/cmr.dir/cid7021.cc.o CMakeFiles/cmr.dir/cid7445.cc.o CMakeFiles/cmr.dir/cid7452.cc.o CMakeFiles/cmr.dir/cid7453.cc.o CMakeFiles/cmr.dir/cid10013.cc.o CMakeFiles/cmr.dir/cid10013e.cc.o CMakeFiles/cmr.dir/cid10033.cc.o CMakeFiles/cmr.dir/cid10033e.cc.o ../../lib/libdcmsr.3.6.1.dylib ../../lib/libdcmimage.3.6.1.dylib ../../lib/libdcmimgle.3.6.1.dylib ../../lib/libdcmdata.3.6.1.dylib ../../lib/liboflog.3.6.1.dylib ../../lib/libofstd.3.6.1.dylib -lpthread
    Undefined symbols for architecture x86_64:
      "DSRTree<DSRDocumentTreeNode>::getRoot() const", referenced from:
          vtable for TID1001_ObservationContext in tid1001.cc.o
          vtable for TID1204_LanguageOfContentItemAndDescendants in tid1204.cc.o
          vtable for TID1600_ImageLibrary in tid1600.cc.o
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [lib/libcmr.3.6.1.dylib] Error 1
    make: *** [cmr/fast] Error 2
    //---------------

    [1] http://llvm.org/releases/download.html#3.1
//--------------

git-svn-id: http://svn.slicer.org/Slicer4/trunk@24587 3bd1e089-480b-0410-8dfb-8563597acbee