ENH: Update CTK tag
2011-07-13  Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>

  * Libs/Core/CMake/ctkMacroBFDCheck.cmake: Log message when either bfd header
  or library is not found

  * Libs/Core/CMake/TestBFD/CMakeLists.txt,
  Libs/Core/CMake/ctkMacroBFDCheck.cmake: Use BFD instead BDF to identify CMake
  variable related to BinaryFileDescriptor

  * Libs/Core/CMake/TestBFD/CMakeLists.txt,
  Libs/Core/CMake/TestBFD/TestBFD.cpp, Libs/Core/CMake/ctkMacroBFDCheck.cmake,
  Libs/Core/ctk_library_options.cmake: CTKCore - Add library options and
  implement a more robust detection of libbfd  Two advanced CMake options
  associated with CTKCore library are now exposed to the developer:
  CTK_LIB_Core_WITH_BFD_STATIC CTK_LIB_Core_WITH_BFD_SHARED  Enabling one of
  these options will build CTKCore library with BFD support, in other words,
  that means the CTKCore will include the class ctkBinaryFileDescriptor.h (See
  CTK/Libs/Core/ctkBinaryFileDescriptor.h)  More detailed regarding Binary File
  Descriptor are available here:
  http://en.wikipedia.org/wiki/Binary_File_Descriptor_library  If
  CTK_LIB_Core_WITH_BFD_STATIC is enabled, the static version of bfd library
  will be searched (libbfd.a) so that CTKCore can be linked against it. If not
  found or if the library header are not installed or if the associated
  "try_compile" failed to pass, a CMake Warning will be displayed. For example:
   //------------------ CMake Warning at
  Libs/Core/CMake/ctkMacroBFDCheck.cmake:69 (MESSAGE): warning: CTKCore: Failed
  to enable BFD support.  Disabling CTKCore WITH_BFD_STATIC library option.
  See

  ild-log.txt for more details. Call Stack (most recent call first):
  Libs/Core/CMakeLists.txt:12 (INCLUDE) -- CTKCore: BFD support disabled
  //------------------   Similarly, if CTK_LIB_Core_WITH_BFD_SHARED is enabled,
  the shared version of the library will try to be used (libbfd.so)   Let's
  also note that these two options are mutually exclusive. If enabled
  simultaneously, a CMake Fatal error will be displayed.  For example:
  //------------------ CMake Error at Libs/Core/CMake/ctkMacroBFDCheck.cmake:7
  (MESSAGE): error: Options WITH_BFD_STATIC and WITH_BFD_SHARED are mutually
  exclusive ! hint: Enable either WITH_BFD_STATIC or WITH_BFD_SHARED. Call
  Stack (most recent call first):  Libs/Core/CMakeLists.txt:12 (INCLUDE)
  //------------------   The rational ...  Before that change a call to
  "find_package(bfd)" was used in TestBFD try_compile test.  Either the static
  or dynamic version of the library were found.  In case only the static
  version of the library was found and if CTK was build as shared library, this
  was causing error like the one reported below:  //------------------
  /usr/bin/ld: error:
  /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/libbfd.a(format.o):
  requires unsupported dynamic reloc; recompile with -fPIC ... /usr/bin/ld:
  /usr/lib/gcc/x86_64-linux-gnu/4.4.3/../../../../lib/libbfd.a(bfd.o): in
  function bfd_errmsg:../../bfd/bfd.c:484: error: undefined reference to
  'xstrerror' ... //------------------  These link errors are due to the fact
  the static version of the bfd library installed on the system is not built
  using the "-fPIC" flag.  As explained in [1]: "Usually, shared libraries must
  be compiled in a special way, for position-independence (PIC). Because a
  shared library may be mapped into memory at different locations each time it
  is loaded, addresses within the library would be variable. Therefore, all
  addresses inside the library are stored zero-based, relative to the beginning
  of the library. A register is then set aside to contain that address, so that
  all references in the library can be easily computed at runtime.  This is
  also a frequent source of errors: Using non-PIC code in a shared library does
  not always cause an error. It even works sometimes, but may cause weird
  problems on occasion. However, it is never a problem to use PIC code outside
  a shared library. " [1] http://www.fpx.de/fp/Software/tcl-c++/tcl-c++.html
  See also http://www.physics.uq.edu.au/people/foster/amd64_porting.html   To
  conclude, providing these two new CTKCore options: WITH_BFD_STATIC and
  WITH_BFD_SHARED allows a better control over the build of CTK and enforce the
  fact that BFD support has to be explicitly enabled.  This approach is also
  more deterministic and ensure to have a similar default build configuration.
  Indeed, BFD support in CTKCore will be enabled on demand instead of being
  enabled if possible.    On unix, option WITH_SHARED could be easily tested
  using the following one-liner: Note: Make sure to update the location of
  qmake before running this one liner  git clone
  git://github.com/commontk/CTK.git CTK-BFD-WithShared-Test  && cd
  CTK-BFD-WithShared-Test && git checkout
  origin/ctkcore-implement-robust-libbfd-test && cd .. && mkdir
  CTK-BFD-WithShared-Test-build && cd CTK-BFD-WithShared-Test-build && cmake
  -DQT_QMAKE_EXECUTABLE:PATH=/home/jchris/Projects/qtsdk-2010.05/qt/bin/qmake
  -DCTK_LIB_PluginFramework:BOOL=OFF -DCTK_LIB_Core_WITH_BFD_SHARED:BOOL=ON
  -DCTK_LIB_Core_WITH_BFD_STATIC:BOOL=OFF -DBUILD_TESTING:BOOL=OFF
  ../CTK-BFD-WithShared-Test && make -j4 && cd ..   On unix, option WITH_STATIC
  could be easily tested using the following one-liner: Note: Make sure to
  update the location of qmake before running this one liner  git clone
  git://github.com/commontk/CTK.git CTK-BFD-WithStatic-Test  && cd
  CTK-BFD-WithStatic-Test && git checkout
  origin/ctkcore-implement-robust-libbfd-test && cd .. && mkdir
  CTK-BFD-WithStatic-Test-build && cd CTK-BFD-WithStatic-Test-build && cmake
  -DQT_QMAKE_EXECUTABLE:PATH=/home/jchris/Projects/qtsdk-2010.05/qt/bin/qmake
  -DCTK_LIB_PluginFramework:BOOL=OFF -DCTK_LIB_Core_WITH_BFD_SHARED:BOOL=OFF
  -DCTK_LIB_Core_WITH_BFD_STATIC:BOOL=ON -DBUILD_TESTING:BOOL=OFF
  ../CTK-BFD-WithStatic-Test && make -j4 && cd ..

2011-07-13  Julien Finet <julien.finet@kitware.com>

  * Libs/Widgets/ctkPopupWidget.cpp, Libs/Widgets/ctkPopupWidget.h: Rename
  windowAlpha/windowGeometry into effectAlpha/effectGeometry

  * Libs/Widgets/Testing/Cpp/ctkPopupWidgetTest1.cpp,
  Libs/Widgets/ctkPopupWidget.cpp: Make sure we match the end geometry with the
  pixmap geometry  The openGeometry is actually a desired geometry. If the
  popup ends up being bigger than the desired geometry (because of its
  minimumSize), we need to resize the pixmap for the popup effect to take it
  into account.

  * Libs/Widgets/ctkPopupWidget.cpp, Libs/Widgets/ctkPopupWidget.h: Add
  ctkPopupWidget::pinPopup(bool)  It appears that having setAutoHide as a slot
  is not that usefull as we want the opposite behavior.

2011-07-12  Julien Finet <julien.finet@kitware.com>

  * Libs/Widgets/ctkPopupWidget.h: ctkPopupWidget::setAutoHide is now a slot
  It can be conveniently connected with a button toggled signal.

  * Libs/Widgets/Plugins/ctkPopupWidgetPlugin.cpp: ctkPopupWidgetPlugin was not
  allowing more than 1 child  As soon as the mouse moved outside ctkPopupWidget
  (in the Designer), the widget was hidden and no more widgets could be added.

2011-07-11  Steve Pieper <pieper@bwh.harvard.edu>

  * Applications/ctkDICOM/ctkDICOMMain.cpp, .../ctkDICOMQueryRetrieveMain.cpp,
  .../Widgets/ctkDICOMQueryResultsTabWidget.cpp,
  Libs/DICOM/Widgets/ctkDICOMQueryResultsTabWidget.h,
  .../Testing/Cpp/ctkDateRangeWidgetTest1.cpp,
  Libs/Widgets/ctkDateRangeWidget.cpp, Libs/Widgets/ctkDateRangeWidget.h: Fix
  copyright on some files  Change to Isomics copyright for files originally
  written by Steve Pieper (for the record, these were base on examples
  developed by Kitware people and on work from the Qt developers at
  Nokia/Trolltech).

2011-07-09  Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>

  * .../Testing/Cpp/ctkDICOMApplicationTest1.cpp,
  Applications/ctkDICOM/ctkDICOMMain.cpp,
  [...]
  .../LastConfigureStep/CTKGenerateCTKConfig.cmake: Use
  http://www.apache.org/licenses/LICENSE-2.0.txt instead of
  http://www.commontk.org/LICENSE

  * .../Testing/Cpp/ctkDICOMApplicationTest1.cpp,
  .../ctkSimplePythonShell/ctkSimplePythonManager.h,
  .../ctkSimplePythonQtDecorators.h, .../ctkSimplePythonShellMain.cpp,
  .../ctkTestWrappedQInvokable.h, .../ctkTestWrappedQListOfVTKObject.h,
  .../ctkSimplePythonShell/ctkTestWrappedQProperty.h,
  .../ctkSimplePythonShell/ctkTestWrappedSlot.h,
  .../ctkTestWrappedVTKQInvokable.h,
  .../ctkSimplePythonShell/ctkTestWrappedVTKSlot.h: Add missing license header
  to Applications files

  * .../Cpp/ctkBinaryFileDescriptorTestHelper.cpp,
  .../Core/Testing/Cpp/ctkCommandLineParserTest1.cpp,
  Libs/Core/ctkCommandLineParser.cpp, Libs/Core/ctkCommandLineParser.h,
  Libs/Core/ctkPimpl.h: Add missing license header to Libs/Core files

  * Libs/DICOM/Core/Testing/Cpp/ctkDICOMTest1.cpp,
  .../DICOM/Core/Testing/Cpp/ctkDICOMTesterTest1.cpp,
  .../DICOM/Core/Testing/Cpp/ctkDICOMTesterTest2.cpp,
  Libs/DICOM/Core/ctkDICOMDataset.cpp, Libs/DICOM/Core/ctkDICOMPersonName.cpp,
  Libs/DICOM/Core/ctkDICOMPersonName.h,
  .../Widgets/Testing/Cpp/ctkDICOMImageTest1.cpp,
  Libs/DICOM/Widgets/ctkDICOMQueryWidget.cpp: Add missing license header to
  Libs/DICOM files

  * .../Testing/Cpp/ctkDicomAppHostingTypesTest1.cpp,
  .../Cpp/ctkDicomObjectLocatorCacheTest1.cpp: Add missing license header to
  Plugins/org.commontk.dah.core files

  * .../ctkQtMobilityServiceActivator.cpp,
  .../ctkQtMobilityServiceActivator_p.h: Add missing license header to
  Plugins/org.commontk.qtmobility.service files

  * Plugins/org.commontk.eventbus/ctkEventBusImpl.cpp,
  Plugins/org.commontk.eventbus/ctkEventBusImpl_p.h,
  .../org.commontk.eventbus/ctkEventBusPlugin.cpp,
  .../org.commontk.eventbus/ctkEventBusPlugin_p.h,
  .../ctkEventHandlerWrapper_p.h: Add missing license header to
  Plugins/org.commontk.eventbus files

  * .../VTK/Core/Testing/Cpp/ctkVTKConnectionTest1.cpp,
  .../Cpp/ctkVTKObjectEventsObserverTest1.cpp,
  .../VTK/Core/Testing/Cpp/ctkVTKObjectTest1.cpp,
  .../Core/Testing/Cpp/ctkVTKObjectTestHelper.cpp,
  .../VTK/Core/Testing/Cpp/ctkVTKObjectTestHelper.h,
  .../Cpp/vtkLightBoxRendererManagerTest1.cpp,
  .../VTK/Core/vtkLightBoxRendererManager.cpp,
  .../VTK/Core/vtkLightBoxRendererManager.h: Add missing license header to
  Libs/Visualization/VTK/Core files

  * Libs/Core/ctkCheckableModelHelper.h,
  Libs/Scripting/Python/Widgets/ctkPythonConsole.cpp,
  Libs/Scripting/Python/Widgets/ctkPythonConsole.h,
  Libs/Widgets/ctkCheckBoxPixmaps.cpp, Libs/Widgets/ctkCheckBoxPixmaps.h,
  Libs/Widgets/ctkCheckableHeaderView.cpp,
  Libs/Widgets/ctkCheckableHeaderView.h, Libs/Widgets/ctkConsole.cpp,
  Libs/Widgets/ctkConsole.h, Libs/Widgets/ctkSettings.cpp,
  Libs/Widgets/ctkSettings.h, Libs/Widgets/ctkToolTipTrapper.cpp,
  Libs/Widgets/ctkToolTipTrapper.h: Use URL to refer to ParaView license
  version 1.2

  * Libs/Core/ctkCheckableModelHelper.h,
  Libs/Scripting/Python/Widgets/ctkPythonConsole.cpp,
  Libs/Scripting/Python/Widgets/ctkPythonConsole.h,
  Libs/Widgets/ctkCheckBoxPixmaps.cpp, Libs/Widgets/ctkCheckBoxPixmaps.h,
  Libs/Widgets/ctkCheckableHeaderView.cpp,
  Libs/Widgets/ctkCheckableHeaderView.h, Libs/Widgets/ctkConsole.cpp,
  Libs/Widgets/ctkConsole.h, Libs/Widgets/ctkSettings.cpp,
  Libs/Widgets/ctkSettings.h, Libs/Widgets/ctkToolTipTrapper.cpp,
  Libs/Widgets/ctkToolTipTrapper.h: Fix indent in "Module" attribute associated
  with Paraview license header

  * Libs/Core/ctkBinaryFileDescriptor.cpp, Libs/Core/ctkBinaryFileDescriptor.h:
  ctkBinaryFileDescriptor - Remove BWH Copyright year and fix indent

  * .../Testing/Cpp/ctkVTKThumbnailViewTest1.cpp: Update license header
  associated with ctkVTKThumbnailViewTest1

git-svn-id: http://svn.slicer.org/Slicer4/trunk@17489 3bd1e089-480b-0410-8dfb-8563597acbee