COMP: Fix macOS compilation error disabling extra BRAINSTools CLIs
Following the update of BRAINSTools in r26341, three additional modules
are available: BRAINSDemonWarp, VBRAINSDemonWarp and BRAINSRefacer

This commit disables them and avoids the follow build error on macOS:

```
Standard Error
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0-build/BRAINSTools/BRAINSRefacer/BRAINSRefacer.cxx:5:
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/Filtering/DisplacementField/include/itkTransformToDisplacementFieldFilter.h:21:
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/Core/Common/include/itkDataObjectDecorator.h:31:
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/Core/Common/include/itkDataObject.h:31:
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/Core/Common/include/itkObject.h:31:
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/Core/Common/include/itkLightObject.h:23:
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/Core/Common/include/itkTimeStamp.h:33:
In file included from /Users/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/Core/Common/include/itkAtomicInt.h:38:
/Users/kitware/Dashboards/Nightly/Slicer-0-build/ITKv4/Modules/Core/Common/include/itkAtomicIntDetail.h:42:11: fatal error: 'atomic' file not found
# include <atomic>
          ^
1 error generated.
```

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26353 3bd1e089-480b-0410-8dfb-8563597acbee