COMP: Fix build error related to qSlicerSegmentationsReader
This commit fixes build error and warning introduced by r26868 (ENH: Allow loading
STL files as segmentation node)

/path/to/Slicer/Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx:121:5: error: ‘vtkNew’ was not declared in this scope
     vtkNew<vtkSTLReader> reader;
     ^
/path/to/Slicer/Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx:121:24: error: expected primary-expression before ‘>’ token
     vtkNew<vtkSTLReader> reader;
                        ^
/path/to/Slicer/Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx:121:26: error: ‘reader’ was not declared in this scope
     vtkNew<vtkSTLReader> reader;
                          ^
/path/to/Slicer/Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx:136:22: error: expected primary-expression before ‘>’ token
     vtkNew<vtkSegment> segment;
                      ^
/path/to/Slicer/Modules/Loadable/Segmentations/qSlicerSegmentationsReader.cxx:136:24: error: ‘segment’ was not declared in this scope
     vtkNew<vtkSegment> segment;
                        ^


                                    ^

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26870 3bd1e089-480b-0410-8dfb-8563597acbee