BUG: Fixed typo that caused ExtensionWizard error
Fixes this error:

$ bin/SlicerExtensionWizard
Traceback (most recent call last):
  File "bin/../libexec/Slicer-4.4/ExtensionWizard.py", line 10, in <module>
    w.execute()
  File "C:\Program Files\Slicer 4.4.0-2014-12-30\bin\Python\SlicerWizard\ExtensionWizard.py", line 695, in execute
    self._execute(args if len(args) else None)
  File "C:\Program Files\Slicer 4.4.0-2014-12-30\bin\Python\SlicerWizard\ExtensionWizard.py", line 602, in _execute
    initLogging(logging.getLogger(), args)
  File "C:\Program Files\Slicer 4.4.0-2014-12-30\bin\Python\SlicerWizard\Utilities.py", line 204, in initLogging
    logger.setLevel(logLevel)
NameError: global name 'logLevel' is not defined

git-svn-id: http://svn.slicer.org/Slicer4/trunk@23850 3bd1e089-480b-0410-8dfb-8563597acbee