BUG: Fix MacOSX Packaging to avoid failure to import compiled python module.
This commit should fix the regression introduced in r25947 [1] by ensuring the
variables PYTHON_STDLIB_SUBDIR and  PYTHON_SITE_PACKAGES_SUBDIR are
defined in the fixup script.

[1] ENH: Introduce PYTHON_STDLIB_SUBDIR and PYTHON_SITE_PACKAGES_SUBDIR CMake vars

It will prevents message like this one from being reported when installing
and starting Slicer from generated installer:

```
code for hash md5 was not found.
Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
```

Thanks to

Isaiah Norton <inorton@bwh.harvard.edu>
Andriy Fedorov <fedorov@bwh.harvard.edu>
Steve Pieper <pieper@isomics.com>

for their help investigating.

git-svn-id: http://svn.slicer.org/Slicer4/trunk@25996 3bd1e089-480b-0410-8dfb-8563597acbee