COMP: Fix Linux build error in vtkMRMLColorLogic
This commit fixes a build error introduced in r24742 (ENH: Add terminology
information to color picker in Editor)

/path/to/Slicer/Libs/MRML/Logic/vtkMRMLColorLogic.cxx:1402:26: error: ‘find_if’ is not a member of ‘std’
   ret.erase(ret.begin(), std::find_if(ret.begin(),ret.end(),
                          ^
/path/to/Slicer/Libs/MRML/Logic/vtkMRMLColorLogic.cxx:1404:13: error: ‘find_if’ is not a member of ‘std’
   ret.erase(std::find_if(ret.rbegin(),ret.rend(),
             ^
/path/to/Slicer/Libs/MRML/Logic/vtkMRMLColorLogic.cxx: In member function ‘bool vtkMRMLColorLogic::ParseTerm(std::string, vtkMRMLColorLogic::StandardTerm&)’:
/path/to/Slicer/Libs/MRML/Logic/vtkMRMLColorLogic.cxx:1428:14: error: ‘count’ is not a member of ‘std’
   size_t n = std::count(str.begin(), str.end(), ';');
              ^

git-svn-id: http://svn.slicer.org/Slicer4/trunk@24745 3bd1e089-480b-0410-8dfb-8563597acbee