STYLE: Fix style of ITK classes using KWStyle
This commit introduced the style Utilities/KWStyle/ITK.kws.xml based of
the official ITK Style.

Style was checked using the following command:

  for file in $(find . | ack-grep "\/itk.+(h|cpp|txx|cxx)$"); do
    KWStyle -gcc -xml ./Utilities/KWStyle/ITK.kws.xml $file;
  done

KWStyle was built from source: https://github.com/Kitware/KWStyle

The following errors remain:

  ./Modules/CLI/ExpertAutomatedRegistration/ITKRegistrationHelper/itkAnisotropicSimilarity3DTransform.h:109: error: Internal variable (itk::Rigid3DTransform<TScalarType>::SetMatrix) doesn't match regular expression (m_[A-Z])
  ./Modules/CLI/ResampleDTIVolume/Testing/itkTestMainExtended.h:17: error: namespace not defined

git-svn-id: http://svn.slicer.org/Slicer4/trunk@25829 3bd1e089-480b-0410-8dfb-8563597acbee