COMP: Update CTK to fix windows build error.
//---------------------------------
Fix windows build errors related to relocation of classes

This commit update the export macro according to accommodate the
relocation of the classes done in commit 448aaf3

Error were similar to the report below:

.\moc_ctkHistogram.cxx(40) : error C2491: 'ctkHistogram::staticMetaObject' : definition of dllimport static data member not allowed
//---------------------------------

git-svn-id: http://svn.slicer.org/Slicer4/trunk@23259 3bd1e089-480b-0410-8dfb-8563597acbee