COMP: Update CTK - Fixes windows build error
Error that will be fixed:

31>6>4>..\..\..\..\CTK\Libs\Widgets\ctkTestApplication.cpp(129) : error C2228: left of '.toLocal8Bit' must have class/struct/union
31>6>4>        type is 'const char *'


All other changes:

$ git shortlog dc9fd81..383c477 --no-merges
Andreas Fetzer (6):
      Added support for modification time in xnat
      Adaptions to changes in qRestAPI
      Cleanup
      Added support for resources for all levels of the xnat data hierachy
      Fixed reconstruction to diplay content properly
      Cleanup

Jean-Christophe Fillion-Robin (1):
      Fix build of ctkTestApplication.cpp with Qt4. Fixes #482

Sascha Zelzer (7):
      Always use brackets for if statements.
      Fix unused parameter warning.
      qRegisterMetaType ctkServiceReference and QSharedPointer<ctkPlugin>, because the weakness of Qt MetaType system, we need to     register type early.
      Break the #include <QtSql> into     #include <QLibrary>     #include <QSqlQuery>     #include <QDebug>     #include <QSqlError>     #include <QPluginLoader>     #include <QDirIterator>     because Qt
      Work around different wchar_t settings.
      Use ascii ' instead unicode ‘’
      Fix ctkConsoleTest for Qt5.

Yonggang Luo (6):
      Move the REGISTERED macro check to the front of the ctkServiceEvent file.
      It's should return T() but QVariant().
      Add the lost Q_D(const PluginTracker); in ctkPluginTracker<T>::isEmpty()
      Use unicode version FormatMessageW in ctkPluginFrameworkLauncher::appendPathEnv
      Use ascii ' instead of unicode ’ in file ctkEventAdmin.h
      use GetProcAddress to safe calling to RtlCaptureStackBackTrace in ctkBackTrace.cpp

git-svn-id: http://svn.slicer.org/Slicer4/trunk@23262 3bd1e089-480b-0410-8dfb-8563597acbee