COMP: Install pyconfig.h required to install distribute in an installed tree
It will fix the following error:

error: invalid Python installation: unable to open /home/jchris/Projects/Slicer4-Superbuild-Debug/Slicer-build/_CPack_Packages/linux-amd64/TGZ/Slicer-4.1.0-2012-10-15-linux-amd64/lib/Python/include/python2.6/pyconfig.h (No such file or directory)
Something went wrong during the installation.

occurring when install distribute applying the following steps:

1) curl -O http://python-distribute.org/distribute_setup.py
2) ./Slicer --launch /usr/bin/python2.6 distribute_setup.py

Note: A different error occurs when "distribute_setup.py" is executed
directly using Slicer executable:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 8, in <module>
    os.chdir(os.path.dirname(os.path.abspath(__file__)))
NameError: name '__file__' is not defined

This is tracked by issue #2649

See http://www.na-mic.org/Bug/view.php?id=2636

Fixes #2636

git-svn-id: http://svn.slicer.org/Slicer4/trunk@21191 3bd1e089-480b-0410-8dfb-8563597acbee