COMP: Fix invalid operand build error in qSlicerSettingsStylesPanel
This commit fixes the following error introduced by r26829 (BUG: Fix
Slicer style setting display)

/path/to/Slicer/Base/QTGUI/qSlicerSettingsStylesPanel.cxx: In function ‘QString {anonymous}::toCamelCase(const QString&)’:
/path/to/Slicer/Base/QTGUI/qSlicerSettingsStylesPanel.cxx:163:18: error: no match for ‘operator==’ (operand types are ‘const QChar’ and ‘const char [2]’)
     if (s[i - 1] == " ")
                  ^

git-svn-id: http://svn.slicer.org/Slicer4/trunk@26833 3bd1e089-480b-0410-8dfb-8563597acbee