BUG: helper method does not have access to slicer module
Before this change, calling the method from a module gave this error:

"/Applications/Slicer-2014-02-07.app/Contents/bin/Python/slicer/util.py",
line 383, in resetSliceViews
    manager = slicer.app.layoutManager().resetSliceViews()
    NameError: global name 'slicer' is not defined

Importing slicer in each method seems wrong so,
TODO: explore importing at the top of util.py

git-svn-id: http://svn.slicer.org/Slicer4/trunk@22941 3bd1e089-480b-0410-8dfb-8563597acbee