COMP: turn off MD5 for LibArchive build
With MacOSX 10.15 MD5 is deprecated so LibArchive fails
to build with the errors listed below.  This fix turns off
MD5 and allows the build to go ahead.  I don't believe
we use MD5 with LibArive, only with python and cmake, so
this should have no side effects.

/Users/pieper/slicer/latest/sbrew/LibArchive/libarchive/archive_digest.c:162:3: error: 'CC_MD5_Init' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
  CC_MD5_Init(ctx);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:133:12: note: 'CC_MD5_Init' has been explicitly marked deprecated here
extern int CC_MD5_Init(CC_MD5_CTX *c)
           ^
/Users/pieper/slicer/latest/sbrew/LibArchive/libarchive/archive_digest.c:162:3: error: 'CC_MD5_Init' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
  CC_MD5_Init(ctx);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:133:12: note: 'CC_MD5_Init' has been explicitly marked deprecated here
extern int CC_MD5_Init(CC_MD5_CTX *c)
           ^
/Users/pieper/slicer/latest/sbrew/LibArchive/libarchive/archive_digest.c:170:3: error: 'CC_MD5_Update' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
  CC_MD5_Update(ctx, indata, insize);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:136:12: note: 'CC_MD5_Update' has been explicitly marked deprecated here
/Users/pieper/slicer/latest/sbrew/LibArchive/libarchive/archive_digest.c:170:3: error: 'CC_MD5_Update' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
extern int CC_MD5_Update(CC_MD5_CTX *c, const void *data, CC_LONG len)
           ^
  CC_MD5_Update(ctx, indata, insize);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:136:12: note: 'CC_MD5_Update' has been explicitly marked deprecated here
extern int CC_MD5_Update(CC_MD5_CTX *c, const void *data, CC_LONG len)
           ^
/Users/pieper/slicer/latest/sbrew/LibArchive/libarchive/archive_digest.c:177:3: error: 'CC_MD5_Final' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
  CC_MD5_Final(md, ctx);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:139:12: note: 'CC_MD5_Final' has been explicitly marked deprecated here
/Users/pieper/slicer/latest/sbrew/LibArchive/libarchive/archive_digest.c:177:3: error: 'CC_MD5_Final' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
extern int CC_MD5_Final(unsigned char *md, CC_MD5_CTX *c)  CC_MD5_Final(md, ctx);

           ^  ^

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:139:12: note: 'CC_MD5_Final' has been explicitly marked deprecated here
extern int CC_MD5_Final(unsigned char *md, CC_MD5_CTX *c)
           ^
3 errors generated.
3 errors generated.
make[5]: *** [libarchive/CMakeFiles/archive.dir/archive_digest.c.o] Error 1
make[5]: *** [libarchive/CMakeFiles/archive_static.dir/archive_digest.c.o] Error 1

From: Steve Pieper <pieper@isomics.com>

git-svn-id: http://svn.slicer.org/Slicer4/trunk@28523 3bd1e089-480b-0410-8dfb-8563597acbee