BUG: Revert "ENH: Create new view to embed DICOM browser in main widget"
This reverts commit f1ddec2d7f5d5f92c42e94ace8affbca2b6afb27.

There are some testing issues on Mac (slicer.app.layoutManager().registerViewFactory(self.viewFactory) - AttributeError: 'NoneType' object has no attribute 'registerViewFactory') and we would make some more improvements before making this change.

git-svn-id: http://svn.slicer.org/Slicer4/trunk@28407 3bd1e089-480b-0410-8dfb-8563597acbee